name: Package and Create Artifact

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["release-ci"]
    branches: [ master ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install WIX toolset
        run: |
          Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
          Start-Process -FilePath ".\wix311.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Run clean build with Maven
        run: mvn clean package

      - name: Extract version from pom.xml file
        id: version-extractor
        uses: dostonhamrakulov/maven-artifact-version-extractor@v1.0
        with:
          file_path: ${{ github.workspace }}/pom.xml

      - name: Project version
        run: echo "Version ${{ steps.version-extractor.outputs.version }}"

      - name: Create package directory
        run: mkdir -p target/package

      - name: Create JavaFX application installer artifact
        run: |
          jpackage --input target/ `
            --name InfirmaryApplication `
            --main-jar "infirmary-application-${{ steps.version-extractor.outputs.version }}.jar" `
            --type exe `
            --dest target/package `
            --win-menu `
            --win-shortcut `
            --module-path "target/lib" `
            --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base `
            --app-version "${{ steps.version-extractor.outputs.version }}" `
            --vendor "RoCS" `
            --description "Infirmary Desktop Application" `
            --win-dir-chooser `
            --verbose `

      - name: Upload the installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: InfirmaryApplication-Installer
          path: target/package/InfirmaryApplication-*.exe

